name: GitHub Actions Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a sample command
        run: echo "Hello, GitHub Actions!"
